alias normi='sh ~/Documents/my_script/script/norminette.sh'
alias groutine='sh ~/script/script/groutine.sh'
alias compilette="sh ~/Documents/my_script/script/compilette.sh"
alias labo="cd ~/Documents/my_script/"
alias quote="sh ~/Documents/my_script/script/quotilette.sh"
alias cl="clear"
alias killtask="~/script/script/killtask.sh"
